### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ErwanScraft** [HighestDreams/Emojis#2]
Why is it that every time I use an emoji it appears like this

![Screenshot_2021-09-09-09-22-57-011_com mojang minecraftpe](https://user-images.githubusercontent.com/72255518/132612028-2d4bd27c-ff34-49c5-bf20-0fa4f7ea2ff3.jpg)

**Comment by HighestDreams** [comment]
<p>Sounds weird because it just happened to you! And for someone else this did not happen, it seems like you are riding emoji instead emoji must ride you! please <strong>change</strong> </p><code>$pk->link = new EntityLink($player->getId(), $npc->getId(), EntityLink::TYPE_RIDER, true, true);</code><p>to</p><code>$pk->link = new EntityLink($npc->getId(), $player->getId(), EntityLink::TYPE_RIDER, true, true);</code><p> and try again.</p>

https://github.com/HighestDreams/Emojis/blob/main/src/HighestDreams/Emojis/Main.php#L117
